services:
  video-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    restart: unless-stopped

# Optional: Add Redis for job queue (recommended for production)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped